### ISSUE TITLE
First draft

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/2023-ecosystem-paper#1]
@pauladkisson has volunteered to get the first draft of this paper started

My recommended structure would be

1) Abstract
2) Intro/background - cite previous works on NWB+DANDI, general data sharing in science
3) The problem of achieving near-universal read ability from proprietary file formats into common APIs and our current solutions (neo, roiextractors, OpenCV, and the leftover custom bits of NeuroConv that cover the gaps) - lots of room to talk about all the challenges that can occur
4) How we've tackled efficiently writing high volumes back to disk in a standardized format (largely stuff we solved years ago, mostly in HDMF, but still plenty to talk about that hasn't been published, like optimized chunking, compression (can cite Alessio's paper and probably Yatsenko's by the time this gets done), and buffering
5) The ongoing challenge of variety of temporal alignment; Satra knew of other packages common in neuroimaging that people used to solve the problem years ago, but question remains why every group these days sets up their own custom way of doing it for a given experiment
6) Spread the 'how' of NeuroConv solution throughout previous sections, but now highlight the challenges resulting from NeuroConv itself (requires Python and some coding experience, even if minimal) and how GUIDE seeks to solve them; may also comment on how it makes problem of specifying rich metadata more convenient

**Comment by pauladkisson** [comment]
Thanks for jumpstarting this, structure looks good. I will be putting out together a detailed outline to kick us off -- PR coming soon.

**Comment by pauladkisson** [comment]
**See notes from biweekly meeting with Ben**:
Work on paper on NeuroConv, NWB Inspector, and the NWB GUIDE


NWB and DANDI have a lot of benefits

The fundamental challenge of using NWB and DANDI is conversion from myriad formats to NWB

Difficult to automate:
Variety
Complexity (often multiple streams)
Volume

Different audiences that require different tools: PyNWB is more flexible, NeuroConv is automated but requires programming experience, NWB GUIDE is fully automated and requires no programming experience, but less flexible

Approach of NeuroConv
Modular
Efficiently handles large datasets
Automatically applies good chunking and compression

3 Goals / Target Audiences:
Overview of software suite for Users
Peer-reviewed reference for citations/grants/etc.
Detailed account of technical challenges and solutions for RSE peers
